name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        nodejsversion: ["15"]
        scalaversion: ["2.11.12", "2.12.11", "2.13.2"]
        project: ["scalajs-js-envs", "scalajs-js-envs-test-kit", "scalajs-env-nodejs"]
        include:
          - nodejsversion: "16"
            scalaversion: "2.12.11"
            project: "scalajs-env-nodejs"
          - nodejsversion: "17"
            scalaversion: "2.12.11"
            project: "scalajs-env-nodejs"
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          java-version: 8
          distribution: adopt
      - uses: sbt/setup-sbt@v1
      - uses: actions/setup-node@v5
        with:
          node-version: "${{ matrix.nodejsversion }}"
      - uses: coursier/cache-action@v6
      - name: Test
        run: sbt "++${{ matrix.scalaversion }}" ${{ matrix.project }}/test
      - name: Doc generation
        run: sbt "++${{ matrix.scalaversion }}" ${{ matrix.project }}/doc
      - name: MiMa
        run: sbt "++${{ matrix.scalaversion }}" ${{ matrix.project }}/mimaReportBinaryIssues
      - name: Header check
        run: sbt "++${{ matrix.scalaversion }}" ${{ matrix.project }}/headerCheck ${{ matrix.project }}/test:headerCheck
